services:
  database:
    image: postgres:15-alpine

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tms
    
    ports:
      - "5432:5432"
    
    volumes: 
      - database:/var/lib/postgresql/data


  specbox:

    build: 
      context: . 
      dockerfile: Dockerfile
    image: "pk72/spec-box:${VERSION:-0.1.1}"
    command: dotnet ./SpecBox.WebApi.dll --urls=http://+:80
    ports: 
      - "80:80"
    depends_on:
      - database



volumes:
  database:
    driver: local
